// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApROWAdcVKOPYMgbeMSUf9pZzg84r8z0g',
    appId: '1:312512693346:web:d0b98bb132876952157d3b',
    messagingSenderId: '312512693346',
    projectId: 'nnnn-3d324',
    authDomain: 'nnnn-3d324.firebaseapp.com',
    storageBucket: 'nnnn-3d324.firebasestorage.app',
    measurementId: 'G-ZXG1R00NNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdEHlNN5oTteHy3nObPxbM-bUe1xqxsBg',
    appId: '1:312512693346:android:097431f1dade436b157d3b',
    messagingSenderId: '312512693346',
    projectId: 'nnnn-3d324',
    storageBucket: 'nnnn-3d324.firebasestorage.app',
    databaseURL: 'https://nnnn-3d324-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ2-hKFeEuriV07y3jNG6faP_Kudzs6Hg',
    appId: '1:312512693346:ios:18a6c20d536b0ee8157d3b',
    messagingSenderId: '312512693346',
    projectId: 'nnnn-3d324',
    storageBucket: 'nnnn-3d324.firebasestorage.app',
    iosBundleId: 'com.example.solo1',
    databaseURL: 'https://nnnn-3d324-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ2-hKFeEuriV07y3jNG6faP_Kudzs6Hg',
    appId: '1:312512693346:ios:18a6c20d536b0ee8157d3b',
    messagingSenderId: '312512693346',
    projectId: 'nnnn-3d324',
    storageBucket: 'nnnn-3d324.firebasestorage.app',
    iosBundleId: 'com.example.solo1',
    databaseURL: 'https://nnnn-3d324-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApROWAdcVKOPYMgbeMSUf9pZzg84r8z0g',
    appId: '1:312512693346:web:598662b4bcbbd626157d3b',
    messagingSenderId: '312512693346',
    projectId: 'nnnn-3d324',
    authDomain: 'nnnn-3d324.firebaseapp.com',
    storageBucket: 'nnnn-3d324.firebasestorage.app',
    measurementId: 'G-VHG1S484RS',
    databaseURL: 'https://nnnn-3d324-default-rtdb.firebaseio.com',
  );
}
